apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: information
spec:
  backgroundColor: {{ .Values.backgroundColor }}
  color: {{ .Values.color }}
  location: {{ .Values.location }}
  text: >-
    {{ .Values.text }}
